### PR TITLE
Committing new DLLs

### PR DESCRIPTION
**Pull request by nikhilchandra**
This pull request covers fixes to the 32- and 64-bit DLLs for Plexon's PL2FileReader library.

### CODE REVIEW

**Comment by zm711** [comment]
This seems fine to me, but I'll defer to @h-mayorquin to merge it since he works with Plexon the most for us.

**Comment by h-mayorquin** [comment]
Can you describe the fixes here or link to changes so we can keep provenance?

**Comment by h-mayorquin** [comment]
Maybe we can use this file as provenance:

https://github.com/NeuralEnsemble/pypl2/blob/master/bin/bin-readme.md

That is, can you write on that file why the files needed to be modified.

**Comment by nikhilchandra** [comment]
The DLLs have always supported the PL2_GetAnalogChannelDataSubset function, it's just that we never really exposed it in the Python API until relatively recently. There was a problem with the DLLs' implementation that caused the subset function's performance to lag under certain conditions -- these new DLLs fix the problem.

**Comment by h-mayorquin** [comment]
Can you add exactly the lines you wrote (copy paste) in this file:

https://github.com/NeuralEnsemble/pypl2/blob/master/bin/bin-readme.md

and this is good to go for me.

**Comment by nikhilchandra** [comment]
Done!

**Comment by nikhilchandra** [comment]
Hi @h-mayorquin , is this ready to be pulled?

**Comment by h-mayorquin** [comment]
Yes, I was waiting for your response on email about whether you would like to have code so people can pull the latest version available. But let's propagate this as it is and then improve it.

**Comment by nikhilchandra** [comment]
Oh yes, sorry for the confusion. I think of the code we discussed via email as separate from this DLL commit. Agreed -- we will proceed iteratively. Thanks!

**Pull request merged**
